### ISSUE TITLE
Timer doesn't update when frame has no focus

### ISSUE THREAD

**Issue by Hoodoo** [TatriX/pomidor#4]
I like the module a lot, so much as I have it running on one of secondary displays. However I've noticed that once the buffer has no focus, it would stop updating after ~ 8 minutes.

What might cause this and how to fix it?

**Comment by TatriX** [comment]
Hm, timer should work. Probably it was somehow canceled. Maybe add some custom logging to `pomidor--cancel-timer` to find why it was called.

**Comment by Hoodoo** [comment]
Sorry, I've phrased it the wrong way. The timer keeps working. The buffer does not update. Once it gets focus, it gets updated based on timer.

**Comment by Hoodoo** [comment]
I've also figured out that it has nothing to do with time.

I run emacs server, the buffer stops updating once any other frame gets focus. I'm afraid it has something to do with emacs itself and can't be fixed within the module.

**Comment by accidentalrebel** [comment]
Hi guys, I tried it out and for me the timer stops updating immediately after switching frames. As described by @Hoodoo, the timer still runs but the updating stops. When I go back to the frame that the *pomidor* buffer is on then it starts updating again.

Since this package was inspired by [Tomatinho](https://github.com/konr/tomatinho). I tried running that package and saw that the timer still works even if the frame is out of focus. Maybe Tomatinho uses a different method of updating that Pomidor can also use?

I'll give the code a check if I find the time.

**Comment by accidentalrebel** [comment]
So I gave it a check and found out that the reason why the timer is not updating when the frame is out of focus is because the `get-buffer-window` under the `pomidor--render` function does not consider all windows on all existng frames.

Adding `t` to the argument fixes this issue as seen below:
``` emacs-lisp
(defun pomidor--render ()
  "Render pomidor state."
  (let ((buffer (pomidor--get-buffer-create)))
    (when (get-buffer-window buffer t)
      (with-current-buffer buffer
         ...
```

I'll send a pull request in a bit.
